### ISSUE TITLE
Refactor get_speech_option_birth_day util 

### ISSUE THREAD

**Issue by imsickofmaps** [praekeltfoundation/mama-ng-jsbox#28]
Currently pulls vars from flow and causes bug:

Steps to Reproduce: 
1) Register as a currently pregnant mom. 
2) Choose May as the birth month. May is confirmed correctly. 
3) Choose any day as the birth date. The date "x of April" is confirmed, instead of May as expected. 

Note: This may be happening with moms who have already had their babies, too, but didn't check that path. 

https://praekelt.atlassian.net/projects/MNG/issues/MNG-30

**Comment by gsvr** [comment]
- [x] Rename `state_r08_birth_day_5.mp3` to `state_r08_birth_day_4.mp3`
- [x] Upload `state_r08_birth_day_5.mp3` when received from Sheetal.
