### ISSUE TITLE
Dockerfile: fix installation of node modules

### ISSUE THREAD

**Issue by JayH5** [praekeltfoundation/mama-ng-jsbox#80]
`Error: Cannot find module 'vumigo_v02'`

**Comment by JayH5** [comment]
**Why this is not working:**
We do a `vm.runInNewContext()` [here](https://github.com/praekelt/vumi-sandbox/blob/vxsandbox-0.6.0/vxsandbox/sandboxer.js#L110) ([docs](https://nodejs.org/docs/v0.10.0/api/vm.html#vm_vm_runinnewcontext_code_sandbox_filename)) to run the sandboxed code. Unfortunately, this resets a whole lot of context before running. The current working directory is lost and so is the `NODE_PATH` environment variable. Which means node can't find the dependencies in `/app/node_modules`.

**How this was working before:**
Accidentally. We used to install Node modules to `/node_modules`. In the sandbox the current working directory gets reset to `/`, which the `node_modules` directory was in.

**How this is working with @smn 's changes:**
When you do a `npm install --global [<pkg>]` the modules are installed to `/usr/local/lib/node_modules` which is a place that node always looks in.

**The fix:**
We should probably include some logic in [praekelt/vumi-sandbox](https://github.com/praekelt/vumi-sandbox) that picks up the current working directory and passes that through to the sandboxed code. For now, we can probably just copy/move `/app/node_modules` to `/node_modules` or `/usr/local/lib/node_modules`.

**Comment by smn** [comment]
pinging @hodgestar, @miltontony, @rudigiesler & @justinvdm on this so they can follow along as this progresses.

**Comment by hodgestar** [comment]
Any reason why `npm install --global` isn't the correct fix here?

**Comment by smn** [comment]
Just doing an `npm install --global` on the package in `/app` _may_ work, I don't think I've tried that.

**Comment by JayH5** [comment]
`npm install --global` will do..

```
/usr/local/lib/node_modules/mama-ng-jsbox
├── q@0.9.7
├── lodash@2.4.2
├── moment@2.6.0
├── go-jsbox-metrics-helper@0.1.1 (moment@2.5.1)
└── vumigo_v02@0.2.17 (jed@0.5.5)
```

Note that the dependencies are within the `mama-ng-jsbox` directory - i.e. `vumigo_v02` is installed to `/usr/local/lib/node_modules/mama-ng-jsbox/node_modules/vumigo_v02`, not `/usr/local/lib/node_modules/vumigo_v02`. The source is also copied into `/usr/local/lib/node_modules/mama-ng-jsbox`.

In this case, the sandboxed app will still not be able to find dependencies. `npm` is kind of a pain as it has almost no configuration options at all.
